# Generated by Django 3.1.4 on 2021-02-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_auto_20210217_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
