# Generated by Django 3.1.4 on 2021-02-21 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_post_post_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_picture',
        ),
    ]
