# Generated by Django 3.1.4 on 2021-02-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_remove_post_post_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameContato', models.CharField(max_length=255, null=True)),
                ('EmailContato', models.CharField(max_length=255, null=True)),
                ('PhoneContato', models.CharField(max_length=20, null=True)),
                ('MensagemContato', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
