# Generated by Django 2.2.13 on 2021-03-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0013_auto_20210314_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
